services:
  embedding_service:
    container_name: embedding_service
    image: dhoaibao/embedding_service:latest
    ports:
      - "5000:5000"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dhoaibao
      POSTGRES_DB: toystore
    ports:
      - "5432:5432"
    volumes:
      - /home/dhoaibao/DockerData/databases/postgresql:/var/lib/postgresql/data