name: Deploy to VMs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy code mới
        uses: actions/checkout@v3

      - name: Thiết lập SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy lên VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            cd ~/ToyStore/ToyStore-Backend
            git pull origin main

            # Install Bun if not already installed
            if ! command -v bun &> /dev/null; then
              echo "Installing Bun..."
              curl -fsSL https://bun.sh/install | bash
              # Add Bun to PATH (adjust based on your shell, e.g., for zsh)
              echo 'export PATH="$HOME/.bun/bin:$PATH"' >> ~/.zshrc
              source ~/.zshrc
            fi

            # Install PM2 if not already installed
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              npm install -g pm2
            fi

            bun install

            pm2 restart toystore-backend
          EOF